modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
[[mods]] #mandatory
modId="calamos" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
authors="${mod_authors}" #optional
[[mixins]]
config="calamos.mixins.json"
description='''${mod_description}'''
[[dependencies.calamos]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.calamos]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.calamos]]
    modId="fusion"
    type="required"
    versionRange="[${fusion_version},)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.calamos]]
    modId="terrablender"
    type="required"
    versionRange="[${terrablender_version},)"
[[dependencies.calamos]]
    modId="curios"
    type="required"
    versionRange="[${curios_version},)"
